-- Tạo bảng inventory_history
CREATE TABLE IF NOT EXISTS inventory_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    total_inventory INTEGER NOT NULL
);

-- Cho phép REST API thao tác trên bảng
ALTER TABLE inventory_history ENABLE ROW LEVEL SECURITY;

-- Cấp quyền ẩn danh đọc data (cho Dashboard)
CREATE POLICY "Cho phép đọc ẩn danh"
ON inventory_history FOR SELECT
TO anon
USING (true);

-- Cấp quyền ghi data (cho Edge Functions / Github Actions)
CREATE POLICY "Cho phép ghi"
ON inventory_history FOR INSERT
TO service_role
WITH CHECK (true);
